---
title: "sailing_demographics"
output: html_document
date: "2024-05-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
suppressWarnings(TRUE)
library(readr)
library(ggh4x)
library(afex)
library(Rmisc)
library(dplyr)
library(kableExtra)
library(tidyr)
library(ggplot2)
library(reshape2)
library(sjPlot)
```

Age, Gender, and Race demographics data for included participants 
```{r demographics data}
demographics_data <- read_csv("../data/sailing/demographics.csv")

age_demographics <- demographics_data %>%
  group_by(categorical_age) %>%
  summarise(n = n(),
            min_age = min(Age),
            max_age = max(Age),
            mean_age = round(mean(Age),2),
            median_age = round(median(Age),2),
            n_females = sum(Gender=='Female'))
age_demographics

race_percentages <- demographics_data %>%
  group_by(Race) %>%
  summarise(Percentage = round((n() / nrow(demographics_data) * 100),1))
race_percentages

demographics_data %>%
  summarise(percent_hispanic = round(mean(Hispanic=='Y')*100,1))
```
