---
title: "demographics"
output: html_document
date: "2024-05-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
library(readr)
library(ggh4x)
library(afex)
library(Rmisc)
library(dplyr)
library(sjPlot)
library(tidyr)
library(pROC)
```

## Experiment 1 Demographics
Age, Gender, and Race demographics data for included participants 
```{r experiment demographics }
demographics_data <- read_csv("../data/experiment1_rest/demographics.csv", show_col_types = FALSE)

age_demographics <- demographics_data %>%
  group_by(categorical_age) %>%
  summarise(n = n(),
            min_age = round(min(Age),2),
            max_age = round(max(Age),2),
            mean_age = round(mean(Age),2),
            n_females = sum(Gender=='Female'))
age_demographics

race_percentages <- demographics_data %>%
  group_by(Race) %>%
  summarise(Percentage = round((n() / nrow(demographics_data) * 100),1))
race_percentages

demographics_data %>%
  summarise(percent_hispanic = round((mean(Hispanic=='Y')*100),1))
```

## Experiment 2 Demographics
``` {r experiment 2 demographics}
demographics_data <- read_csv("../data/experiment2_norest/demographics.csv", show_col_types = FALSE)

age_demographics <- demographics_data %>%
  group_by(categorical_age) %>%
  summarise(n = n(),
            min_age = round(min(Age),2),
            max_age = round(max(Age),2),
            mean_age = round(mean(Age),2),
            n_females = sum(Gender=='Female'))
age_demographics

race_percentages <- demographics_data %>%
  group_by(Race) %>%
  summarise(Percentage = round((n() / nrow(demographics_data) * 100),1))
race_percentages

demographics_data %>%
  summarise(percent_hispanic = round((mean(Hispanic=='Y')*100),1))
```